-- Creating New Database
CREATE DATABASE spotify_analytics_db;
USE spotify_analytics_db;

-- Creating table through query because manually all data is not uploading 
CREATE TABLE spotify_tracks (
    row_index INT,                  
    track_id VARCHAR(50),
    artists TEXT,
    album_name TEXT,
    track_name TEXT,
    popularity INT,
    duration_ms INT,
    explicit VARCHAR(10),           -- Boolean values 
    danceability DECIMAL(5,4),
    energy DECIMAL(5,4),
    `key` INT,
    loudness DECIMAL(5,3),
    `mode` INT,
    speechiness DECIMAL(5,4),
    acousticness DECIMAL(5,4),
    instrumentalness DECIMAL(7,6),
    liveness DECIMAL(5,4),
    valence DECIMAL(5,4),
    tempo DECIMAL(6,3),
    time_signature INT,
    track_genre VARCHAR(50)
);
-- Selecting Database
USE spotify_analytics_db;
-- Loading Dataset 
LOAD DATA LOCAL INFILE 'F:/Data Analytics Real time Project portfolio/Spotify/Spotify_Cleaned_Tracks.csv'
INTO TABLE spotify_tracks
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\r\n'
IGNORE 1 ROWS;

-- Enables the global 'local_infile' system variable to allow loading sanitized datasets directly from the client machine.
SET GLOBAL local_infile = 1;

-- Check the Dataset is upload or not
SELECT * FROM spotify_tracks;

-- Data Cleaning Steps --
 -- 1. Remove any columns or rows --
 -- 2. Remove Duplicates --
 -- 3. Standardize the data --
 -- 4. Null values or blank values --
 
 
-- Step 1. Remove any columns or rows
-- Removing the 'row_index' column generated by Python's index during the CSV export, as it has no analytical value.
ALTER TABLE spotify_tracks 
DROP COLUMN row_index;

-- Checking
SELECT * FROM spotify_tracks;

-- Step 2. Remove Duplicates
-- This step eliminates absolute row-level duplicate entries across the entire dataset. We preserve rows where the same 
-- 'track_id' appears under different 'track_genre' values. This ensures that future analyses on Popular Genres, Audio 
-- Features, Mood Trends, and Artist Popularity remain unbiased and statistically accurate.
-- Create a new staging table containing only unique row combinations
CREATE TABLE spotify_tracks_clean AS
SELECT DISTINCT 
    track_id,
    artists,
    album_name,
    track_name,
    popularity,
    duration_ms,
    explicit,
    danceability,
    energy,
    `key`,
    loudness,
    `mode`,
    speechiness,
    acousticness,
    instrumentalness,
    liveness,
    valence,
    tempo,
    time_signature,
    track_genre
FROM spotify_tracks;

-- 2. Drop the original table containing raw duplicated records
DROP TABLE spotify_tracks;

-- 3. Rename the cleaned staging table to restore the primary schema name
ALTER TABLE spotify_tracks_clean RENAME TO spotify_tracks;

-- 4. Verify the final analytical record count
SELECT COUNT(*) AS total_analysis_ready_records FROM spotify_tracks;

SELECT * FROM spotify_tracks;

-- Step 3. Data Standardization
-- This step standardizes all text columns by performing:
-- Trimming leading/trailing white spaces.
-- Cleaning unwanted special characters (dots, commas, dashes, brackets).
-- Converting text fields to Title Case (First Letter Capital).

-- 1. Disable safe updates temporarily to allow bulk data transformation
SET SQL_SAFE_UPDATES = 0;

-- 2. Remove special characters and clean text layout using REGEXP_REPLACE
UPDATE spotify_tracks
SET 
    -- Removes brackets, dots, dashes, commas, colons, and semicolons
    artists = REGEXP_REPLACE(artists, '[\\.\\,\\-\\(\\)\\[\\]\\:\\;\\/]', ' '),
    album_name = REGEXP_REPLACE(album_name, '[\\.\\,\\-\\(\\)\\[\\]\\:\\;\\/]', ' '),
    track_name = REGEXP_REPLACE(track_name, '[\\.\\,\\-\\(\\)\\[\\]\\:\\;\\/]', ' ');

-- 3. Trim extra spaces (including internal double spaces caused by symbol removal)
UPDATE spotify_tracks
SET 
    artists = TRIM(REGEXP_REPLACE(artists, '[[:space:]]+', ' ')),
    album_name = TRIM(REGEXP_REPLACE(album_name, '[[:space:]]+', ' ')),
    track_name = TRIM(REGEXP_REPLACE(track_name, '[[:space:]]+', ' '));

-- 4. Standardize Text Case: Title Case formatting (First Letter Capital, rest Lowercase)
-- Note: Uses MySQL string manipulation to simulate Proper/Title Case structure
UPDATE spotify_tracks
SET 
    album_name = CONCAT(UPPER(SUBSTRING(album_name, 1, 1)), LOWER(SUBSTRING(album_name, 2))),
    track_name = CONCAT(UPPER(SUBSTRING(track_name, 1, 1)), LOWER(SUBSTRING(track_name, 2))),
    track_genre = CONCAT(UPPER(SUBSTRING(track_genre, 1, 1)), LOWER(SUBSTRING(track_genre, 2)));


-- 5. Re-enable safe updates for database security
SET SQL_SAFE_UPDATES = 1;

SELECT * FROM spotify_tracks;

-- Artist names are in special characters separately
-- 1. Disable safe updates temporarily for text manipulation
SET SQL_SAFE_UPDATES = 0;

-- 2. Capitalize both First and Last Name based on space positions
UPDATE spotify_tracks
SET artists = CASE 
    -- Scenario A: If the artist name contains a space (e.g., 'Ben woodward')
    WHEN LOCATE(' ', artists) > 0 THEN 
        CONCAT(
            UPPER(SUBSTRING(artists, 1, 1)), 
            LOWER(SUBSTRING(artists, 2, LOCATE(' ', artists) - 1)), 
            UPPER(SUBSTRING(artists, LOCATE(' ', artists), 2)), 
            LOWER(SUBSTRING(artists, LOCATE(' ', artists) + 2))
        )
    -- Scenario B: If it is a single name with no spaces (e.g., 'Eminem')
    ELSE 
        CONCAT(
            UPPER(SUBSTRING(artists, 1, 1)), 
            LOWER(SUBSTRING(artists, 2))
        )
END;

-- 3. Re-enable safe updates for database integrity
SET SQL_SAFE_UPDATES = 1;

-- Explicit column is also clean separately
-- 1. Disable safe updates temporarily for data type alignment
SET SQL_SAFE_UPDATES = 0;

-- 2. Map text boolean values to 1 and 0 strings
UPDATE spotify_tracks
SET explicit = CASE 
    WHEN explicit = 'True' OR explicit = '1' THEN '1'
    WHEN explicit = 'False' OR explicit = '0' THEN '0'
    ELSE '0' -- Default fallback for any unexpected blank or null values
END;

-- 3. Re-enable safe updates for database protection
SET SQL_SAFE_UPDATES = 1;

SELECT * FROM spotify_tracks;

-- Step 4 Remove Null Values or Blank Values 
-- Scans the dataset for any structural NULLs or empty strings in critical text fields (artists, album_name, track_name). 
-- Replaces anomalies with a standardized 'Unknown' placeholder to maintain categorization integrity during BI visualization.

-- 1. Disable safe updates temporarily for global dataset updates
SET SQL_SAFE_UPDATES = 0;

-- 2. Handle missing values in Core Text Columns
UPDATE spotify_tracks
SET 
    artists = IF(artists IS NULL OR TRIM(artists) = '', 'Unknown', artists),
    album_name = IF(album_name IS NULL OR TRIM(album_name) = '', 'Unknown', album_name),
    track_name = IF(track_name IS NULL OR TRIM(track_name) = '', 'Unknown', track_name),
    track_genre = IF(track_genre IS NULL OR TRIM(track_genre) = '', 'Unknown', track_genre);

-- 3. Handle missing values in Numerical/Audio Feature Columns (Defensive Design)
UPDATE spotify_tracks
SET 
    popularity = IF(popularity IS NULL, 0, popularity),
    duration_ms = IF(duration_ms IS NULL, 0, duration_ms),
    danceability = IF(danceability IS NULL, 0, danceability),
    energy = IF(energy IS NULL, 0, energy),
    `key` = IF(`key` IS NULL, 0, `key`),
    loudness = IF(loudness IS NULL, 0, loudness),
    `mode` = IF(`mode` IS NULL, 0, `mode`),
    speechiness = IF(speechiness IS NULL, 0, speechiness),
    acousticness = IF(acousticness IS NULL, 0, acousticness),
    instrumentalness = IF(instrumentalness IS NULL, 0, instrumentalness),
    liveness = IF(liveness IS NULL, 0, liveness),
    valence = IF(valence IS NULL, 0, valence),
    tempo = IF(tempo IS NULL, 0, tempo),
    time_signature = IF(time_signature IS NULL, 0, time_signature);

-- 4. Re-enable safe updates for database security
SET SQL_SAFE_UPDATES = 1;

-- last check of final results 
SELECT * FROM spotify_tracks;

SELECT COUNT(*) FROM spotify_tracks;

